### ISSUE TITLE
Version v2.0.0 released

### ISSUE THREAD

**Issue by jorgeborges** [irazasyed/laravel-gamp#1]
Just a heads up. I released v2.0.0 of the php-ga-measurement-protocol package. It uses Guzzle 6 as the HTTP client so it no longer supports PHP 5.4, only 5.5 or above.

I'll maintain a separate branch ```v1``` for version 1 releases, only important fixes will be applied to version 1 branch.

Feel free to do something similar so that users of your package can start using Guzzle 6 which implements the PSR-7 standard.

**Comment by irazasyed** [comment]
Hi @jorgeborges,

Thanks for the heads up. I highly appreciate it :+1: 

Will update the package today as per the changes.

**Comment by irazasyed** [comment]
Released a new version `v1.0` (First major since initial releases) and moved previous one to `0.5` branch which uses `v1` of your library. Thanks again.
