### ISSUE TITLE
cURL error

### ISSUE THREAD

**Issue by grcasanova** [irazasyed/laravel-gamp#12]
Hello,
I am running this library on an Ubuntu VM and I keep getting this error:
`cURL error 7: Failed to connect to ssl.google-analytics.com port 443: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

However, trying a _curl_ to that website works fine.

How to debug it?
Thank you

**Comment by irazasyed** [comment]
Hi,

You've opened the issue here: https://github.com/theiconic/php-ga-measurement-protocol/issues/22

Which is relevant. Because this is simply a bridge for Laravel and those settings are not controlled from this package.

That said, I'll respond to that ticket.

**Comment by grcasanova** [comment]
Yes sorry I realized it was more relevant to open it there. Thank you
