### ISSUE TITLE
How can I get clientId?

### ISSUE THREAD

**Issue by ALTELMA** [irazasyed/laravel-gamp#15]
Long time ago I already used your package, but seems problem with missing GA Client ID.
I not quite sure how to get it.

Now I find it from cookie, but still have problem no GA Client ID sometimes.
Do you have any suggest?

**Comment by irazasyed** [comment]
You can use any randomly generated UUID. Consider using package like this one: https://github.com/ramsey/uuid

If a cookie has the ID, you can use that. Otherwise, Generate a random UUID.

**Comment by ALTELMA** [comment]
I not sure about format UUID is same GA client ID format.
It will be work?

**Comment by irazasyed** [comment]
Yes!

**Comment by ALTELMA** [comment]
Let me check the result and I will be back again.
Thank you for help me ;)

Cheer.
