### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by christophrumpel** [irazasyed/laravel-gamp#18]
Hey, can I set somewhere a proxy for the CURL calls? Greets

**Comment by irazasyed** [comment]
Try the below:

```php
use GuzzleHttp\Client as GuzzleClient;
use TheIconic\Tracking\GoogleAnalytics\Network\HttpClient;

$guzzle = new GuzzleClient(['proxy' => '192.168.16.1:10']);
$httpClient = new HttpClient();
$httpClient->setClient($guzzle);

GAMP::setHttpClient($httpClient);
```

This could actually be better if the library has `setOptions` method. I'll see if I can send a PR to them or if you can, feel free to do so.

Let me know if that works for you (I haven't tested that).

**Comment by christophrumpel** [comment]
Perfect, will try that thx! Cheers

**Comment by christophrumpel** [comment]
Still need to wait to see the results in GA (for some strange reasons for a new account it takes some time before the first events get in) but I don't get errors anymore. So I'm pretty sure it works. Thanks a lot!
