### ISSUE TITLE
IDE can't find the method name,this is a big problem.

### ISSUE THREAD

**Issue by argb** [irazasyed/laravel-gamp#2]

**Comment by irazasyed** [comment]
I'll think about it and look for a solution. Thanks for bringing up the issue!

**Comment by argb** [comment]
@irazasyed yes,I have solved,don't use facade.

**Comment by argb** [comment]
thank you.

**Comment by irazasyed** [comment]
Ok cool.

You can also try this one: https://github.com/barryvdh/laravel-ide-helper
