### ISSUE TITLE
How to reset data?

### ISSUE THREAD

**Issue by unlike777** [irazasyed/laravel-gamp#22]
Why was choose Singlton pattern?
Its absolutly not useable in queue jobs!
There is an accumulation of data, how to reset data in gamp object?

**Comment by alberto-bottarini** [comment]
I agree with unlike777

**Comment by irazasyed** [comment]
I've just released `v1.6`, switched to binding. Should resolve this issue.

**Comment by alberto-bottarini** [comment]
Facades are singleton by design, this won't fix the "reset data" problem.

I think you should add a note in documentation regarding this issue.

If you need to reset data, you should resolve another instance of `Analytics` class.
