### ISSUE TITLE
setUserId doesnt work

### ISSUE THREAD

**Issue by oligirling** [irazasyed/laravel-gamp#23]
I cannot seem to get setUserId to work.

The package this extend (https://github.com/theiconic/php-ga-measurement-protocol#usage) allows for setUserId as well as setClientId. But it seems using `setUserId` doesnt seem to work.

Any idea why this is?

**Comment by irazasyed** [comment]
Please share your current code, it'll help in debugging the issue.

**Comment by oligirling** [comment]
Thanks for the reply.

So this works as expected:
```
        $gamp = GAMP::setClientId( $userId );
        $gamp->setEventCategory($category)
            ->setEventAction($request->route()->getName())
            ->setEventLabel($label)
            ->setIpOverride($request->getClientIp())
            ->sendEvent();
```

But this does not work:
```
        $gamp = GAMP::setUserId( $userId );
        $gamp->setEventCategory($category)
            ->setEventAction($request->route()->getName())
            ->setEventLabel($label)
            ->setIpOverride($request->getClientIp())
            ->sendEvent();
```
