### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by chris-ware** [irazasyed/laravel-gamp#30]
Laravel 8 is due to be released tomorrow. Having checked the upgrade guide, Laravel requires Guzzle V7, but The Iconic's package which this is a layer over is limited to Guzzle V6. Looks like no upgrades for The Iconics packages have been done for quite a few months and that looked to be a one-off.

**Comment by irazasyed** [comment]
I've created a PR https://github.com/theiconic/php-ga-measurement-protocol/pull/89

Let's wait for sometime and see. I couldn't test it tho.

**Comment by irazasyed** [comment]
The PR got merged. So we should be good to go!

https://github.com/irazasyed/laravel-gamp/releases/tag/v1.7 released with Laravel 8 support.

Please create a new issue ticket if you face any issues. Thanks!
