### ISSUE TITLE
Even though my configs are right, I don't get any data in google analytics. Also i check firewall and cors. I dd the response of $gamp. It works but i don't  get any data in google analytics. What's others do i need to check?

### ISSUE THREAD

**Issue by Sithu-Soe** [irazasyed/laravel-gamp#32]

**Comment by irazasyed** [comment]
It takes time for the hits to reflect with GA dashboard. You can verify its working using debugging mode as well as by checking the real-time stats in GA as soon as you make a call, it'll be visible for a few seconds.

Check after sometime to see all your hits.
