### ISSUE TITLE
Validating Hits - Debug Mode

### ISSUE THREAD

**Issue by ricardoper** [irazasyed/laravel-gamp#4]
Hello,

Please, consider implementing a debug mode to validate hits:
https://developers.google.com/analytics/devguides/collection/protocol/v1/validating-hits

Is very usefull in development stage.

Best regards,
Ricardo Pereira.

**Comment by irazasyed** [comment]
Hi Ricardo,

Thanks for the info. 

My package is depended on [PHP GA Measurement Protocol](https://github.com/theiconic/php-ga-measurement-protocol) library. So if they update it to support the above debug mode, then i can add the appropriate settings too.

**Comment by ricardoper** [comment]
Hello @irazasyed ,

Understood... Thanks.

Best regards,
Ricardo Pereira.
