### ISSUE TITLE
All transactions are considered direct traffic

### ISSUE THREAD

**Issue by WebSocialManager** [irazasyed/laravel-gamp#40]
When a credit card purchase is made, my web page redirects the user to the web page of his bank where he authenticates his card. Afterwards, the bank's website directs the user to my website again. At this time I launch the event. The problem is that all events are treated as direct traffic.

**Comment by irazasyed** [comment]
You should open an issue ticket on this [repo](https://github.com/theiconic/php-ga-measurement-protocol)
