### ISSUE TITLE
How to get client id?

### ISSUE THREAD

**Issue by ALTELMA** [irazasyed/laravel-gamp#6]
Sorry for newbie question. I try to get from session or cookie not work. Can you advice me to get it, please.

**Comment by irazasyed** [comment]
Please refer: https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#cid

Not sure from where you're trying to access the client ID but that can be set using a random generated UUID. Refer the docs above.

**Comment by ALTELMA** [comment]
for this "setClientId()" Where can I get it? 

Now I get from javascript 
var clientId = tracker.get('clientId');

I don't know. please example to get it, please.

**Comment by irazasyed** [comment]
You don't get that. You need to set a random generated ID. Even the JS version of Google Analytics simply generates a random number for that browser session and stores that in a cookie to send hits later.

Go through the above link i sent you and this one to understand:
https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id

So the example would be:

```php
$gamp = GAMP::setClientId( '<randomly generated id>' );
$gamp->setDocumentPath( '/page' );
$gamp->sendPageview();
```
