### ISSUE TITLE
Ability to Use Multiple tracking Id?

### ISSUE THREAD

**Issue by kevincobain2000** [irazasyed/laravel-gamp#7]
Hi there, is there a way to use multiple tracking Ids?
Edit - Or a way to provide a custom config when calling GAMP?

**Comment by irazasyed** [comment]
Hey!

Nope, The package doesn't support multiple tracking Ids.

However, What you can do is, Use the laravel's config set method to dynamically set the tracking id before making a call and see if that works for you.

**Comment by kevincobain2000** [comment]
cool that should do! Thanks

**Comment by irazasyed** [comment]
Welcome!
