### ISSUE TITLE
How to send custom dimensions/metrics data?

### ISSUE THREAD

**Issue by gradosevic** [irazasyed/laravel-gamp#9]
I'm sending something like this, but don't get any custom data sent. What am I missing here?       
```php
        $gamp = GAMP::setClientId( '123456' );
        $gamp->setDocumentPath( '/test' );
        $gamp->setIpOverride('123.123.123.123');
        $gamp->setCustomDimension('4',1);
        $gamp->setCustomDimension('5',2);
        $gamp->setCustomMetric('6',1);
        $gamp->setCustomMetric('7',2);
        $gamp->sendPageview();
```

**Comment by irazasyed** [comment]
Unfortunately, I don't really know. Since this is simply a bridge for the ICONIC library. Only they can probably help you. I noticed you already tried to reach them and the ticket is in progress?

https://github.com/theiconic/php-ga-measurement-protocol/issues/14 

I'm closing this ticket for now.

**Comment by gradosevic** [comment]
Thanks for the explanation. I'm still waiting for an answer from authors.

**Comment by irazasyed** [comment]
No problem. I'll keep an eye on the other issue ticket. If there's anything I can do from my end. Please do create a new ticket and I'll handle that.
